#!/bin/zsh
echo "Kopiere filer"
rsync -e ssh -rhvc --progress /Users/paad/GitHub/500pd.github.io/ --exclude=\.DS_Store --exclude=\.git --include=\.htaccess 9.buhm.in:~/hjemmeside/
echo "Kopiering færdig"
